# Generated by Django 5.1.3 on 2024-11-16 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalyst_count', '0002_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
