# Generated by Django 5.1.3 on 2024-11-16 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalyst_count', '0004_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
